export const Data = {
  "20SS1A0401": {
    htno: "20SS1A0401",
    results: [
      {
        subject_code: "15705",
        subject_name: "MICROWAVE AND OPTICAL COMMUNICATIONS LAB",
        internal_marks: "16",
        external_marks: "68",
        total_marks: "84",
        grade: "A+",
        grade_points: "9",
        credits: "1",
      },
      {
        subject_code: "15709",
        subject_name: "SEMINAR",
        internal_marks: "84",
        external_marks: "0",
        total_marks: "84",
        grade: "A+",
        grade_points: "9",
        credits: "1",
      },
      {
        subject_code: "15721",
        subject_name: "INDUSTRIAL ORIENTED MINI PROJECT / SUMMER INTERNSHIP",
        internal_marks: "0",
        external_marks: "98",
        total_marks: "98",
        grade: "O",
        grade_points: "10",
        credits: "2",
      },
      {
        subject_code: "15733",
        subject_name: "PROJECT STAGE - I",
        internal_marks: "21",
        external_marks: "67",
        total_marks: "88",
        grade: "A+",
        grade_points: "9",
        credits: "3",
      },
      {
        subject_code: "157AT",
        subject_name: "BIOMEDICAL INSTRUMENTATION",
        internal_marks: "19",
        external_marks: "56",
        total_marks: "75",
        grade: "A",
        grade_points: "8",
        credits: "3",
      },
      {
        subject_code: "157BF",
        subject_name: "DIGITAL IMAGE PROCESSING",
        internal_marks: "17",
        external_marks: "52",
        total_marks: "69",
        grade: "B+",
        grade_points: "7",
        credits: "3",
      },
      {
        subject_code: "157CM",
        subject_name: "MICROWAVE AND OPTICAL COMMUNICATIONS",
        internal_marks: "19",
        external_marks: "30",
        total_marks: "49",
        grade: "C",
        grade_points: "5",
        credits: "3",
      },
      {
        subject_code: "157DH",
        subject_name: "PROFESSIONAL PRACTICE, LAW & ETHICS",
        internal_marks: "24",
        external_marks: "30",
        total_marks: "54",
        grade: "B",
        grade_points: "6",
        credits: "2",
      },
      {
        subject_code: "157EZ",
        subject_name: "REMOTE SENSING & GIS",
        internal_marks: "22",
        external_marks: "33",
        total_marks: "55",
        grade: "B",
        grade_points: "6",
        credits: "3",
      },
    ],
  },
};
